request_all_users = "/users/all"
request_user = "/users/user"
request_add_user = "/users/add"
request_update_user = "/users/update"
request_delete_user = "/users/delete"
request_login_user = "/users/login"
request_associate_device = "/users/associates"

request_all_devices = "/devices/all"
request_all_for_user = "/devices/user-id"
request_device = "/devices/device"
request_add_device = "/devices/add"
request_update_device = "/devices/update"
request_delete_device = "/devices/delete"

request_all_measurements = "/measurements/all"
request_all_for_device = "/measurements/device-id"
request_measurement = "/measurements/measurement"
request_add_measurement = "/measurements/add"
request_update_measurement = "/measurements/update"
request_delete_measurement = "/measurements/delete"
